version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: ainz
      POSTGRES_PASSWORD: ainz

volumes:
  pg_data: